version: "3"

services:

  runtime-setup:
    image: &image swift-openapi-lambda:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: *image

  shell:
    image: *image
