version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-lambda:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"

  test:
    image: *image

  shell:
    image: *image
