version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-lambda:22.04-5.9.0
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.9.0"

  test:
    image: *image

  shell:
    image: *image

  soundness:
    image: *image    
