# This workflow will build a Swift project on macOS and Linux
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: swift-openapi-lambda-build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_enabled: true
      license_header_check_project_name: "Swift OpenAPI Lambda"
      shell_check_enabled: false
      python_lint_check_enabled: false
      api_breakage_check_container_image: "swift:6.0-noble"
      docs_check_container_image: "swift:6.0-noble"
      format_check_container_image: "swiftlang/swift:nightly-6.0-jammy"
      yamllint_check_enabled: false

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_10_enabled: false
      linux_6_0_enabled: true
      linux_6_1_enabled: true
      linux_nightly_main_enabled: true
      linux_nightly_next_enabled: true
      linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_6_1_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error"

  swift-6-language-mode:
    name: Swift 6 Language Mode
    uses: apple/swift-nio/.github/workflows/swift_6_language_mode.yml@main

  semver-label-check:
    name: Semantic Version label check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check for Semantic Version label
        uses: apple/swift-nio/.github/actions/pull_request_semver_label_checker@main